name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: jungjune276/back-deploy
          stage: main
          yaml: |
            name: back-deploy
            app: node@20
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: connection_url
                  value: mongodb+srv://app:1234@app.retr5ep.mongodb.net/
              ports: "8000"
              install: npm ci --production
              start: node index.js
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
